services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    env_file:
      - .env
    environment:
      - CLUSTER_NAME=hadoop_cluster
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
    networks:
      - data_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    env_file:
      - .env
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - hdfs_datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - data_network

volumes:
  hdfs_namenode:
  hdfs_datanode:

networks:
  data_network:
    driver: bridge
