version: '2'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    env_file:
      - .env
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - data_network

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    depends_on:
      - spark-master
    networks:
      - data_network

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=${SPARK_MASTER_URL}
      - SPARK_WORKER_CORES=${SPARK_WORKER_CORES}
      - SPARK_WORKER_MEMORY=${SPARK_WORKER_MEMORY}
    depends_on:
      - spark-master
    networks:
      - data_network

networks:
  data_network:
    driver: bridge
